name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03d8cfb7bc27b39be9cb881f4e06ae7cb9b5fc4ed9aa69730fa28d380b02d4aa"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
