name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "860b950844ceecbd4c473e6a9a68ccaf3e358c49ab0fbaebb78ffa315ac293dd"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
