name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da83155e133acebc028a32a5525771373d56075c0afbaffe214deec2121f04ab"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
