name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56dd71890bb2a8017e658cd4bc98facdeea59c8b1d5faf8c3da55558aa8166e3"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
