name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2de2d7853e36b4455da3ad8596e474c1eea1d43912a125b956fd40506bc4279c"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
