name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "789ecac0c0dd496e767dae35057aa078e01367e3aa026bd2d74e00322484fbad"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
