name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b336feb95602a17cdca16deb444624be13a41e6f7daf6d9ed3617f040fe5441a"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
