name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdde75001d01c47e743273ddc2cd040149667086a17af9a98e4470de7c09645c"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
