name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18cff40db3dd31911f00ae2edd17316f1bc850971f67c5b54e403b09d636a12d"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
