name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c120bb14a807876c6cbab5b32f2f59f121f6e959cf79eb12b28c63b63d095bf8"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
