name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "729a95232e2adaeb307384dfeefe9e1f4642e04b11c9927d4182161ac1a5927b"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
