name = "Kat's Kitchen Pack"
author = "kittywitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f7cd0f041c071dd607a6f8739c4753b544995e8e6f177d44ee17e58c945921d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.54"

[options]
acceptable-game-versions = ["1.21"]
