name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c4f46b07701b7dacd5f61360ee0b224c21ae1ce405f0790fe5a60f749c1f215"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
