name = "Kat's Kitchen Pack"
author = "kittywitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7107991e9bd55be86edb6e821e90e2e87b886a466621dddc0625ce44bb6e061b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.54"

[options]
acceptable-game-versions = ["1.21"]
