name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7b805375403c5a60b5fc381e41fd28218c31c92eb510f60541d4ba73c6403cd"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
