name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d256c5f2fa639776ffdef234092da666f0554420a347db4534c925dd28365995"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
