name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d66b7d05cafc061fb7abccd13708b8afc45d43a437d786eb2b9c7001905516a"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
