name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e0566f22d19e5d479fee990a1e9778d0d61e36205d5b2f6c7eb598f7b3738a7"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
