name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79f68b0ba3f3400c53ebebf81dbefa9a6d9a4c83fb42239f8b67c9a5047a5433"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
