name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "356426cebab901e29fe7224d8215a4a0f8cc1508c86b706b00cbc3ef28940b18"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
