name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3633377cb5395bb609e583e5933696d9b8e6e3621709513bc19160d5d14ea4f"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
