name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f008ff1d19d5e5c1ff07d5fe21dd34c1be2d7534e5a5050c227610fc91c32bc3"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
