name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e823192a1a9ccb6f438eca3e42082a73a69c9b9ea8a02896f2ef5497c4604858"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
