name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "050ba6fffa8f53e7057789c19be320d3d29355472b25c4e907306db7ba9100f1"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
