name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72f0b8cbac2c4f29c2b5da790d8f46689a4f09b7bbcdd69c4231bc0d85bdecd9"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
