name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "963373bda34376571cd1452dc3f2887ef4c5ed223d60be0f5cdd019bb20268d1"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
