name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cc5c9956264bea49592c7d9778d932afcd79c51df2d0aa09bfbb8148905131f"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
