name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50e859d97cd75a8350569cd51d333971dd161e512e340d1f078d206525b28c73"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
