name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30f754e8fc5e675a5dd85a77f54171b0dc22166317473a734b12a4e6bf5f7683"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
