name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26f6dac8b9c4952e4ab733ad6383466c1f89786d498efa8f307c993f0f2532a8"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
