name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb3ca2d42116105213ce0ccc8d000f2fe57a055fed4388cdca19da5d674d044f"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
