name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b320e73862a135f11531185a549fb1979349b4c25208971bdf9f9e343308185"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
