name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94fd7485b30a5663ba44120fd57bac7d80ef3eb8fae5f9165d6b47c8b2ffba7a"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
