name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46c9631334506cfc1e197e8bf7533e52e29c065c6c23605e3b42396db4a6b88a"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
