name = "Marka Modpack"
author = "it's a real group effort o:"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db6b4cf6a0f4c926ea8ac0e9c9736f10a317eaa12686ed9806bcd4e48d4fca90"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
